// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKJxtmOJAlikxch-bqrFwyV2AK8mYpIRU',
    appId: '1:110531944073:web:fa5d099f9e9e76d0287058',
    messagingSenderId: '110531944073',
    projectId: 'flutter-chat-app-3591e',
    authDomain: 'flutter-chat-app-3591e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3591e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXXilfB3_f7Rr0uU9TUq1fe-qDav2cP8',
    appId: '1:110531944073:android:ba96b4ef967813c0287058',
    messagingSenderId: '110531944073',
    projectId: 'flutter-chat-app-3591e',
    storageBucket: 'flutter-chat-app-3591e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-eqagHOhNPAKFiMmGgHdTvgYGzfFmqY',
    appId: '1:110531944073:ios:44276c92ea70fe6f287058',
    messagingSenderId: '110531944073',
    projectId: 'flutter-chat-app-3591e',
    storageBucket: 'flutter-chat-app-3591e.appspot.com',
    iosClientId: '110531944073-e4lgmja5aa2tci2h7irb9e6rh6941oo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-eqagHOhNPAKFiMmGgHdTvgYGzfFmqY',
    appId: '1:110531944073:ios:a2c72360f21dac53287058',
    messagingSenderId: '110531944073',
    projectId: 'flutter-chat-app-3591e',
    storageBucket: 'flutter-chat-app-3591e.appspot.com',
    iosClientId: '110531944073-fa84k0a6one17dmmlit0d9e26iribnpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApplication1.RunnerTests',
  );
}
